---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Site content
- type: directory
  path: _content
  label: Pages
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Homepage and 404
  create: all
- type: directory
  path: _sample
  label: Sample
  create: all
  match: "**/*"
  templates:
  - handbook-page
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
